version: '3.7'
services:

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong
    environment:
      NODE_ENV: production
      TOKEN_SECRET: <token-secret>
      KONGA_SEED_USER_DATA_SOURCE_FILE: /run/secrets/konga-users
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /run/secrets/konga-kong
    secrets:
      - konga-kong
      - konga-users
    networks:
      - internal
      - bastion
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-1

  kong-migrations:
    image: kong:1.3
    command: kong migrations bootstrap
    depends_on:
    - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: <database-name>
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: <database-password>
      KONG_PG_USER: <database-user>
    networks:
      - internal
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name == germanzero-1

  kong-migrations-up:
    image: kong:1.3
    command: kong migrations up && kong migrations finish
    depends_on:
    - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: <database-name>
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: <database-password>
      KONG_PG_USER: <database-user>
    networks:
      - internal
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.name == germanzero-1

  kong:
    image: kong:1.3
    user: root
    depends_on:
    - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: <database-name>
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: <database-password>
      KONG_PG_USER: <database-user>
    networks:
      - internal
      - kong-net
    ports:
      - "80:8000/tcp"
      - "443:8443/tcp"
    volumes:
      - /var/volumes/kong/backup:/backup
      - /etc/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-1

  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: <database-name>
      POSTGRES_PASSWORD: <database-password>
      POSTGRES_USER: <database-user>
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    stdin_open: true
    tty: true
    networks:
      - internal
    volumes:
      - /var/volumes/kong/postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-1

networks:
  internal:
    driver: overlay
    attachable: true
  kong-net:
    external: true
  bastion:
    external: true
    
secrets:
  konga-kong:
    external: true
  konga-users:
    external: true
