version: "3.6"
services:
  bastion:
    image: binlab/bastion
    hostname: bastion
    networks:
      - bastion
    ports:
      - 22222:22/tcp
    environment:
      PUBKEY_AUTHENTICATION: "true"
      GATEWAY_PORTS: "false"
      PERMIT_TUNNEL: "false"
      X11_FORWARDING: "false"
      TCP_FORWARDING: "true"
      AGENT_FORWARDING: "true"
    volumes:
      - /var/volumes/bastion/sshd_config:/etc/ssh/sshd_config:ro
      - /var/volumes/bastion/authorized_keys:/var/lib/bastion/authorized_keys
      - /var/volumes/bastion/ssh:/usr/etc/ssh:rw
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-1

networks:
  bastion:
    external: true
  