version: '3'

services:

  exporter:
    image: prom/node-exporter:latest
#    ports:
#      - '9100:9100'
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
    deploy:
      mode: global
    networks:
      - status

  prometheus:
    image: prom/prometheus:latest
#    ports:
#      - '9090:9090'
    volumes:
      - /var/volumes/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/volumes/prometheus/data:/prometheus:rw
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - status

  grafana:
    image: grafana/grafana
    user: nobody:nogroup
#    ports:
#      - "3004:3000"
    volumes:
      - /var/volumes/grafana:/var/lib/grafana:rw
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - status
      - bastion
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=<smtp-server-name>
      - GF_SMTP_FROM_ADDRESS=noreply@germanzero.de
      - GF_SMTP_USER=<smtp-server-username>
      - GF_SMTP_PASSWORD=<smtp-server-password>

  cadvisor:
    image: google/cadvisor:latest
#    ports:
#      - '9105:8080'
    volumes:
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk
      - /sys:/sys
      - /var/run:/var/run
      - /:/rootfs
    deploy:
      mode: global
    networks:
      - status

networks:
  status:
  bastion:
    external: true
